"""Rasterize the OFL Inter font into a compact 2-bit coverage atlas.

Run with Pillow installed. Generated data stays in Flash, not SRAM.
"""
from pathlib import Path
from math import ceil
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
data, glyphs, fonts = [], [], []
for size in (12, 16, 24, 36):
    font = ImageFont.truetype(str(ROOT / 'assets/fonts/Inter.ttf'), size)
    # Inter variable axes: optical size, weight. Medium UI text.
    font.set_variation_by_axes([size if size >= 14 else 14, 500])
    ascent, descent = font.getmetrics()
    height = ascent + descent
    fonts.append((len(glyphs), height))
    for code in range(32, 127):
        width = ceil(font.getlength(chr(code))) + 2
        img = Image.new('L', (width, height))
        ImageDraw.Draw(img).text((0, ascent), chr(code), font=font, fill=255, anchor='ls')
        coverage = [(p * 3 + 127) // 255 for p in img.get_flattened_data()]
        offset = len(data)
        for i in range(0, len(coverage), 4):
            chunk = coverage[i:i+4] + [0] * 4
            data.append(sum(chunk[j] << (j * 2) for j in range(4)))
        glyphs.append((offset, width, round(font.getlength(chr(code)))))

lines = ['/* Generated by tools/generate_ui_font.py; Inter is licensed under assets/fonts/OFL.txt. */',
         '#ifndef UI_FONT_DATA_H', '#define UI_FONT_DATA_H',
         'typedef struct { uint32_t offset; uint8_t width, advance; } UiGlyph;',
         'typedef struct { uint16_t first; uint8_t height; } UiFont;',
         'static const UiFont ui_fonts[] = {']
lines += [f'    {{{first}, {height}}},' for first, height in fonts]
lines += ['};', 'static const UiGlyph ui_glyphs[] = {']
lines += [f'    {{{off}, {width}, {advance}}},' for off, width, advance in glyphs]
lines += ['};', 'static const uint8_t ui_font_pixels[] = {']
lines += ['    ' + ','.join(str(v) for v in data[i:i+32]) + ',' for i in range(0,len(data),32)]
lines += ['};', '#endif', '']
(ROOT / 'CM7/Core/Inc/ui_font_data.h').write_text('\n'.join(lines), encoding='utf-8')
print(f'Generated {len(glyphs)} glyphs; {len(data)} bytes of coverage; heights {fonts}')
