"""Compile the supplied monochrome logo into firmware coverage data.

This is a deterministic asset-format conversion, not a redesigned logo.
The original JPEG remains byte-for-byte unchanged. Requires Pillow.
"""
from pathlib import Path
from PIL import Image, ImageOps

root = Path(__file__).resolve().parents[1]
source = root / 'assets/branding/initui-source.jpg'
with Image.open(source) as original:
    ink = ImageOps.invert(original.convert('L'))
    bounds = ink.point(lambda p: 255 if p > 127 else 0).getbbox()
    if bounds is None:
        raise ValueError('Logo has no dark foreground')
    width = 320
    height = round(width * (bounds[3]-bounds[1]) / (bounds[2]-bounds[0]))
    mask = ink.crop(bounds).resize((width, height), Image.Resampling.LANCZOS)
    coverage = [(p * 3 + 127) // 255 for p in mask.get_flattened_data()]

data = []
for start in range(0, len(coverage), 4):
    chunk = coverage[start:start+4] + [0] * 4
    data.append(sum(chunk[j] << (j*2) for j in range(4)))
lines = [
    '/* Generated by tools/generate_ui_logo.py from the user-supplied initUI logo. */',
    '#ifndef UI_LOGO_DATA_H', '#define UI_LOGO_DATA_H',
    f'#define UI_LOGO_WIDTH {width}U', f'#define UI_LOGO_HEIGHT {height}U',
    'static const uint8_t ui_logo_coverage[] = {'
]
lines += ['    '+','.join(map(str, data[i:i+32]))+',' for i in range(0,len(data),32)]
lines += ['};', '#endif', '']
(root / 'CM7/Core/Inc/ui_logo_data.h').write_text('\n'.join(lines), encoding='utf-8')
print(f'Logo coverage: {width}x{height}; {len(data)} bytes; source bounds {bounds}')
